// <auto-generated />
namespace WebApplication4.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NumeMigrare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumeMigrare));
        
        string IMigrationMetadata.Id
        {
            get { return "202505201418494_NumeMigrare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
